.PHONY : push build push release setversion

build:
	platformio run -e $(plat_env)
	cd interface;npm install;npm run build
	platformio run -e $(plat_env) -v -t buildfs 

uploadfs:
	platformio run -e $(plat_env) -t uploadfs

uploadfw:
	platformio run -e $(plat_env) -t upload

monitor: 
	platformio device monitor

upload: | build
	platformio run -e $(plat_env) -t uploadfs
	platformio run -e $(plat_env) -t upload

publish:
	yes | cp -rf .pio/build/$(plat_env)/firmware.bin bin/firmware_$(version)$(plat_env).bin
	yes | cp -rf .pio/build/$(plat_env)/spiffs.bin bin/spiffs_$(version)$(plat_env).bin

push:
	git add .
	git commit -am '$(message)'
	git push

setversion:
	python set_version.py $(version)

release:  | build publish setversion
