.PHONY : push build pull push release setversion

build: | pull
	platformio run
	cd interface;npm install;npm run build
	platformio run -v -t buildfs

uploadfs:
	platformio run -t uploadfs

uploadfw:
	platformio run -t upload

monitor: 
	platformio device monitor

upload: | build
	platformio run -t uploadfs
	platformio run -t upload

publish:
	rm -rf bin/
	mkdir bin/
	cp .pio/build/esp12e/firmware.bin bin/firmware_$(version).bin
	cp .pio/build/esp12e/spiffs.bin bin/spiffs_$(version).bin

pull:
	git pull

push:
	git add .
	git commit -am '$(message)'
	git push

setversion:
	python set_version.py $(version)

release:  | build publish setversion push